buildscript {
  repositories {
    jcenter()
    mavenCentral()
    mavenLocal()
    maven {
      url "https://plugins.gradle.org/m2/"
    }
    maven {
      url "https://maven.google.com/"
    }
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:8.4.1'
    
    // !!! This is a nasty hack !!!
    // But I can't figure out a better way to do this...
    classpath files('../ament_gradle_plugin/build/libs/ament_gradle_plugin-0.7.2.jar')
  }
}

apply plugin: 'com.android.library'
apply plugin: 'org.ros2.tools.gradle'

repositories {
   mavenCentral()
   maven {
      url "https://maven.google.com/"
   }
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

android {
  namespace "org.ros2.android"
  compileSdkVersion 22
  ndkVersion "26.3.11579264"
  
  defaultConfig {
    minSdkVersion 22
    targetSdkVersion 22
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }

  // MY POSTBUILD TASK
  gradle.buildFinished {
      println "*** ENVIRONMENT VARIABLE DUMP ***"
      println System.env
  }
}

